Sprint_2
Sergey-Yurievich/qa_java pull request #1
Opened 2021-11-01 20:16 UTC by Sergey-Yurievich

2021-11-03 13:51 UTC, NickFlexer commented on pom.xml
> +        <dependency>
С какой целью добавлена эта зависимость?

2021-11-03 13:53 UTC, NickFlexer commented on src/main/java/com/example/KittensCount.java
> +    int getKittensCount(int kittensCount);
Этот метод стоит переименовать в setKittensCount

2021-11-03 13:57 UTC, NickFlexer commented on src/main/java/com/example/Lion.java
> +public class Lion extends Animal implements KittensCount {
Оригинальный способ изолировать Lion от Feline)
Возможно, проще был бы такой вариант - инициализировать поле feline  через конструктор Lion

2021-11-03 14:05 UTC, NickFlexer requested changes
Добрый день!

У меня есть пара общих замечаний к работе:

1. стоит добавить в .gitignore папки .idea и target - это уменьшит количество отслеживаемых файлов. Почитай, как можно в .gitignore добавить исключения, чтобы из папки target отслеживалась только директория site

2. В задании есть пункт про процент покрытия кода. Хоть общий процент покрытия у тебя высокий - 87%, но класс Animal явно проверен хуже всех. Стоит добавить на него еще тестов.

2021-11-05 15:19 UTC, NickFlexer commented on .gitignore
> +!target/site/
Отлично!

2021-11-05 15:27 UTC, NickFlexer commented on src/main/java/com/example/Lion.java
> +    public int getKittens() {
В этом месте нужно уточнение!

Обрати внимание на эти два метода:
getKittens() и setKittensCount()

обычно такие пары методов называют геттер и сеттер (getter and setter)
их смысл в том, чтобы дать внешнему коду доступ к работе с приватным полям класса

Метод setKittensCount(), как и любой сеттер, нужен для установки значения в поля. Он принимает входное значение, но не должен ничего возвращать

Метод getKittens() наоборот, не должен иметь параметров, но должен возвращать значение поля

В идеале, оба метода назвать однообразно, либо setKittensCount и getKittensCount, либо setKittens и getKittens

Короче, с этой частью кода необходимо разобраться

2021-11-05 15:29 UTC, NickFlexer requested changes
Спасибо за исправления!

Осталось только поправить замечания, связанные с классом Lion (и интерфейсом KittensCount)

2021-11-06 11:57 UTC, Sergey-Yurievich commented on src/main/java/com/example/Lion.java
> +public class Lion extends Animal implements KittensCount {
Не совсем понял, нужно это было менять. Или достаточно было поменять названия по комментарию ниже. Переделал через конструктор надеюсь, что верно

2021-11-06 18:44 UTC, NickFlexer commented on src/main/java/com/example/Feline.java
> +    public int getKittensCount() {
В классе Lion исправил, а тут нет((((

Будь внимательней к своему коду в дальнейшем

2021-11-06 18:45 UTC, NickFlexer approved these changes
Добрый день!

Я готов поставить зачет

2021-11-06 19:02 UTC, merged